name: Create and sometimes publish Docker image

on:
  push:
    branches:
      - "*"
  pull_request:
  schedule:
    - cron: "0 0 * * 0"

env:
  MINECRAFT_VERSION: 1.20.6
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.MINECRAFT_VERSION }}

      - name: Run Docker image
        run: docker run -d --rm --name fabric-server -e EULA=true ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.MINECRAFT_VERSION }}

      - name: Wait until server is reachable (smoke test)
        run: timeout 60 docker logs -f fabric-server | grep -q "For help, type"

      - name: Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.MINECRAFT_VERSION }}
        if: github.ref == 'refs/heads/main'
